version: '3.6'
services:
  webserver:
    image: nginx
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "80:80"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  dbbackup:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
  web:
    build: .
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: puma
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      ELASTICSEARCH_URL: http://localhost:9200
      MAILER_URL:
      TWITTER_API_CONSUMER_SECRET: 
      TWITTER_API_ACESS_TOKEN_SECRET:  
      VIGILANCE_EMAIL:
      CSV_DATA_KEY: 
