version: '3.6'
services:
  webserver:
    image: nginx
    ports:
      - "80:80"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
  
  web:
    build: .
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: puma
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  kibana:
   image: docker.elastic.co/kibana/kibana:7.6.1
   restart: unless-stopped
   ports:
     - "5601:5601"
   environment:
     - SERVER_PORT=5601
     - ELASTICSEARCH_URL=http://elasticsearch:9200
   depends_on:
     - elasticsearch

volumes:
  esdata:
  environment:
    DATABASE_URL: postgres://postgres@db
