version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - web
  # dbbackup:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      ELASTICSEARCH_URL: http://localhost:9200
      MAILER_URL:
      TWITTER_API_CONSUMER_SECRET: 
      TWITTER_API_ACESS_TOKEN_SECRET:  
      VIGILANCE_EMAIL:
      CSV_DATA_KEY:
      METABASE_SITE_URL: http://localhost:3002
      METABASE_SECRET_KEY: 23610c3bc82d6ee905d43626518368d3df8d90093ac1241742dd7eed7fad4dc2
    links: 
      - db
    networks:
      - web
networks:
  web:
    external: true